name: Issue assignment

on:
  issues:
    types: [opened]

jobs:
  auto-assigned:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issues'
        uses: pozil/auto-assign-issue@v1.0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: AdrianRallBhs
