name: Unit-Testing

on:
  push:
    branches: [main, master, feature/*]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: windows-latest

  steps:
    - name: Testing Unit Tests
    - run: dotnet test
